service: bb2

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: eu-west-1
  memorySize: 128
  timeout: 300
  iamRoleStatements:
    - Effect: Allow
      Action:
      - KMS:Decrypt
      Resource: ${self:custom.kmsSecrets.keyArn}
  environment:
    BB2_API_SECRETS: ${self:custom.kmsSecrets.secrets.bb2api}
    SCHEDULE_HOURS: ${file(config.yml):bb2api.synch.interval}

custom:
  kmsSecrets: ${file(kms-secrets.${opt:stage, self:provider.stage}.${opt:region, self:provider.region}.yml)}

package:
  exclude:
    - examples/**
    - config.yml
    - package.json
    - package-lock.json
    - node_modules/**

functions:
  import-config:
    handler: data/import.import_config

  import-matches:
    handler: data/import.import_matches

  bigbob:
    handler: commentator/commentator.tweet
    environment:
      TWITTER_API_SECRETS: ${self:custom.kmsSecrets.secrets.twitter}

stepFunctions:
  stateMachines:
    data-import:
      events:
        - schedule:
            name: bb2-import
            description: 'Import data from Cyanide'
            rate: rate(${file(config.yml):bb2api.synch.interval} hours)

      definition:
        Comment: "Import data from Cyanide"
        StartAt: import-config
        States:
          import-config:
            ResultPath: $.config
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-import-config"
            Next: import-matches

          import-matches:
            InputPath: $.config
            ResultPath: $.matches
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-import-matches"
            Next: bigbob

          bigbob:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-bigbob"
            End: true

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bb2-config
        AttributeDefinitions:
          - AttributeName: category
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: category
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters
  - serverless-kms-secrets
  - serverless-python-requirements
